# Name of the workflow
name: Unit and Integration tests
# This work flow is triggered when pull requests are opened or updated
on: [ pull_request ]
# A workflow run is made up of one or more jobs.
jobs:
  # id of job, a string that is unique to the "jobs" node above.
  android:
    # The type of machine to run the job on.
    runs-on: macOS-latest
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # A set of different configurations of the virtual  
      # environment.
      matrix:
        api-level:
          - "29"
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: true
    # Contains a sequence of tasks.
    steps:
    # The branch or tag ref that triggered the workflow will be 
    # checked out.
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
    # Sets up Java
    # https://github.com/actions/setup-java
    - name: Java 8 Setup
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8.x'
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'
        channel: 'stable' # or: 'dev' or 'beta'
    # Unit Tests
    - name: Run Unit Tests
      run: flutter test
    # Integration Tests
    - name: "Run Flutter Driver tests"
#     run: "flutter drive --target=test_driver/app.dart"
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: flutter drive --target=test_driver/app.dart
